import type { IGridResponse, IGridTitleResponse } from "../interfaces";

export const dummyGridData: IGridResponse = {
  page: 1,
  per_page: 10,
  items: [
    {
      hidden_driver_id: 363,
      driver_name: "Rejaul Karim (CSS-2056) (CD-23-03-000010)",
      driver_mobile: "01760042967",
      driver_address: null,
      driving_license_no: "00",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 362,
      driver_name: "Md. Bodair Munshi (CSS-1500) (CD-23-03-000009)",
      driver_mobile: "01997918878",
      driver_address: null,
      driving_license_no: "9577940852",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 361,
      driver_name: "Md. Faruk Mollah (CSS-2085) (CD-23-03-000008)",
      driver_mobile: "01953179192",
      driver_address: null,
      driving_license_no: "00",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 341,
      driver_name: "Al Mamun Sarder (CSS-2001) (CD-23-03-000007)",
      driver_mobile: "01814638693",
      driver_address: null,
      driving_license_no: "4637020167",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 321,
      driver_name: "Md. Bodair Munshi (CD-23-03-000006)",
      driver_mobile: "01997918878",
      driver_address: null,
      driving_license_no: "9577940852",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 304,
      driver_name: "Md. Saiful Islam (CSS-1868) (CD-23-03-000005)",
      driver_mobile: "01824441187",
      driver_address: null,
      driving_license_no: "7815119297",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 303,
      driver_name: "Rent A Car-3 (CD-23-03-000004)",
      driver_mobile: "00",
      driver_address: null,
      driving_license_no: "00",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 302,
      driver_name: "Rent A Car-2 (CD-23-03-000003)",
      driver_mobile: "00",
      driver_address: null,
      driving_license_no: "00",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 301,
      driver_name: "Rent A Car-1 (CD-23-03-000002)",
      driver_mobile: "00",
      driver_address: null,
      driving_license_no: "00",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
    {
      hidden_driver_id: 282,
      driver_name: "SHEIKH MOSHARRF HOSSAIN (CSS-1121) (CD-23-03-000001)",
      driver_mobile: "01716616568",
      driver_address: null,
      driving_license_no: "00",
      license_issue_place: null,
      license_expiry_date: null,
      zone_name: "Currency Management Department (Dhaka)",
      hidden_operating_zone_id: 25,
      action: {
        buttons: "Create,Edit,Delete",
      },
    },
  ],
};

export const dummyTitleData: IGridTitleResponse = {
  master_grid_title: "Drivers List",
  total_item: 103,
  export_excel: 1,
  export_pdf: 1,
  export_csv: 0,
  export_printing: 1,
  client_side: 0,
  page_customize: "10, 20, 50, 100",
  checkbox: 1,
  selectable: 1,
  is_column_customizable: 1,
  serial: 0,
  action_table: "cit_drivers",
  primary_key_field: "hidden_driver_id",
  master_column_title_for_app: null,
  items: [],
  attributes: ["hidden_driver_id", "hidden_operating_zone_id"],
  columns: [
    {
      title: "Name",
      sortable: true,
      text_align: "left",
      field_type: "text",
      dataIndex: "driver_name",
      key: "driver_name",
      link: false,
    },
    {
      title: "Mobile",
      sortable: true,
      text_align: "left",
      field_type: "text",
      dataIndex: "driver_mobile",
      key: "driver_mobile",
      link: false,
    },
    {
      title: "Address",
      sortable: true,
      text_align: "left",
      field_type: "text",
      dataIndex: "driver_address",
      key: "driver_address",
      link: false,
    },
    {
      title: "License NO",
      sortable: true,
      text_align: "left",
      field_type: "text",
      dataIndex: "driving_license_no",
      key: "driving_license_no",
      link: false,
    },
    {
      title: "Issue Place",
      sortable: true,
      text_align: "left",
      field_type: "text",
      dataIndex: "license_issue_place",
      key: "license_issue_place",
      link: false,
    },
    {
      title: "expire Date",
      sortable: true,
      text_align: "left",
      field_type: "date",
      dataIndex: "license_expiry_date",
      key: "license_expiry_date",
      link: false,
    },
    {
      title: "Operational Zone",
      sortable: true,
      text_align: "left",
      field_type: "text",
      dataIndex: "zone_name",
      key: "zone_name",
      link: false,
    },
  ],
  buttons: [
    {
      btn_name: "Create",
      btn_type: "button",
      route_link: null,
      btn_class: "btn btn-primary",
      btn_id: "createDriver",
      btn_order: "2",
      btn_icon: "fa fa-plus",
      btn_slug: "create_driver",
      always_show: 1,
      in_dropdown: 0,
      enable_status: null,
      disable_status: null,
      enable_multiple: 1,
      btn_data_attr: null,
    },
    {
      btn_name: "Edit",
      btn_type: "button",
      route_link: null,
      btn_class: "btn btn-primary",
      btn_id: "editDriver",
      btn_order: "3",
      btn_icon: "fa fa-edit",
      btn_slug: "edit_driver",
      always_show: 0,
      in_dropdown: 0,
      enable_status: null,
      disable_status: null,
      enable_multiple: 0,
      btn_data_attr: null,
    },
    {
      btn_name: "Delete",
      btn_type: "button",
      route_link: null,
      btn_class: "btn btn-primary",
      btn_id: "deleteDriver",
      btn_order: "4",
      btn_icon: "fa fa-trash",
      btn_slug: "delete_driver",
      always_show: 0,
      in_dropdown: 0,
      enable_status: null,
      disable_status: null,
      enable_multiple: 1,
      btn_data_attr: null,
    },
  ],
  search_panel: {
    prefix: true,
    session_filter: "0",
    search_fields: [
      {
        search_panel_detail_id: 326,
        search_panel_slug: "cit_drivers_filter",
        company_id: 1,
        column_space: 6,
        label_name: "Driver Code",
        label_class: "form-label",
        input_type: "text",
        input_name: "driver_code",
        input_default_val: null,
        input_id: "driver_code",
        input_class: "form-control",
        input_placeholder: "Driver Code",
        input_operation_type: "WHERE LIKE",
        single_compare: 0,
        sorting: 1,
        required: 0,
        dropdown_slug: null,
        dropdown_options: "0",
        multiple: 0,
        created_by: 11,
        updated_by: null,
        deleted_by: null,
        created_at: "2000-01-19T05:47:58.000Z",
        updated_at: null,
        deleted_at: null,
        status: 1,
        module_id: 8,
      },
      {
        search_panel_detail_id: 327,
        search_panel_slug: "cit_drivers_filter",
        company_id: 1,
        column_space: 6,
        label_name: "Driver Name",
        label_class: "form-label",
        input_type: "text",
        input_name: "driver_name",
        input_default_val: null,
        input_id: "driver_name",
        input_class: "form-control",
        input_placeholder: "Driver Name",
        input_operation_type: "WHERE LIKE",
        single_compare: 0,
        sorting: 2,
        required: 0,
        dropdown_slug: null,
        dropdown_options: "0",
        multiple: 0,
        created_by: 11,
        updated_by: null,
        deleted_by: null,
        created_at: "2000-01-19T05:47:58.000Z",
        updated_at: null,
        deleted_at: null,
        status: 1,
        module_id: 8,
      },
      {
        search_panel_detail_id: 329,
        search_panel_slug: "cit_drivers_filter",
        company_id: 1,
        column_space: 6,
        label_name: "Driver Mobile",
        label_class: "form-label",
        input_type: "text",
        input_name: "driver_mobile",
        input_default_val: null,
        input_id: "driver_mobile",
        input_class: "form-control",
        input_placeholder: "Driver Mobile",
        input_operation_type: "WHERE LIKE",
        single_compare: 0,
        sorting: 3,
        required: 0,
        dropdown_slug: null,
        dropdown_options: "0",
        multiple: 0,
        created_by: 11,
        updated_by: null,
        deleted_by: null,
        created_at: "2000-01-19T05:47:58.000Z",
        updated_at: null,
        deleted_at: null,
        status: 1,
        module_id: 8,
      },
      {
        search_panel_detail_id: 330,
        search_panel_slug: "cit_drivers_filter",
        company_id: 1,
        column_space: 6,
        label_name: "Driver Address",
        label_class: "form-label",
        input_type: "text",
        input_name: "driver_address",
        input_default_val: null,
        input_id: "driver_address",
        input_class: "form-control",
        input_placeholder: "Driver Address",
        input_operation_type: "WHERE LIKE",
        single_compare: 0,
        sorting: 4,
        required: 0,
        dropdown_slug: null,
        dropdown_options: "0",
        multiple: 0,
        created_by: 11,
        updated_by: null,
        deleted_by: null,
        created_at: "2000-01-19T05:47:58.000Z",
        updated_at: null,
        deleted_at: null,
        status: 1,
        module_id: 8,
      },
      {
        search_panel_detail_id: 331,
        search_panel_slug: "cit_drivers_filter",
        company_id: 1,
        column_space: 6,
        label_name: "Driving License No",
        label_class: "form-label",
        input_type: "text",
        input_name: "driving_license_no",
        input_default_val: null,
        input_id: "driving_license_no",
        input_class: "form-control",
        input_placeholder: "Driving License No",
        input_operation_type: "WHERE LIKE",
        single_compare: 0,
        sorting: 5,
        required: 0,
        dropdown_slug: null,
        dropdown_options: "0",
        multiple: 0,
        created_by: 11,
        updated_by: null,
        deleted_by: null,
        created_at: "2000-01-19T05:47:58.000Z",
        updated_at: null,
        deleted_at: null,
        status: 1,
        module_id: 8,
      },
      {
        search_panel_detail_id: 332,
        search_panel_slug: "cit_drivers_filter",
        company_id: 1,
        column_space: 6,
        label_name: "License Issue Place",
        label_class: "form-label",
        input_type: "text",
        input_name: "license_issue_place",
        input_default_val: null,
        input_id: "license_issue_place",
        input_class: "form-control",
        input_placeholder: "License Issue Place",
        input_operation_type: "WHERE LIKE",
        single_compare: 0,
        sorting: 6,
        required: 0,
        dropdown_slug: null,
        dropdown_options: "0",
        multiple: 0,
        created_by: 11,
        updated_by: null,
        deleted_by: null,
        created_at: "2000-01-19T05:47:58.000Z",
        updated_at: null,
        deleted_at: null,
        status: 1,
        module_id: 8,
      },
      {
        search_panel_detail_id: 334,
        search_panel_slug: "cit_drivers_filter",
        company_id: 1,
        column_space: 6,
        label_name: "License Expiry Date",
        label_class: "form-label",
        input_type: "date_range",
        input_name: "license_expiry_date",
        input_default_val: null,
        input_id: "license_expiry_date",
        input_class: "form-control",
        input_placeholder: "License Expiry Date",
        input_operation_type: "WHERE DATERANGE",
        single_compare: 0,
        sorting: 7,
        required: 0,
        dropdown_slug: null,
        dropdown_options: "0",
        multiple: 0,
        created_by: 11,
        updated_by: null,
        deleted_by: null,
        created_at: "2000-01-19T05:47:58.000Z",
        updated_at: null,
        deleted_at: null,
        status: 1,
        module_id: 8,
      },
      {
        search_panel_detail_id: 335,
        search_panel_slug: "cit_drivers_filter",
        company_id: 1,
        column_space: 6,
        label_name: "Operating Zone",
        label_class: "form-label",
        input_type: "dropdown",
        input_name: "operating_zone_id",
        input_default_val: null,
        input_id: "operating_zone_id",
        input_class: "form-control",
        input_placeholder: "Operating Zone",
        input_operation_type: "WHERE EQUAL",
        single_compare: 0,
        sorting: 8,
        required: 0,
        dropdown_slug: "zone_list",
        dropdown_options: "1",
        multiple: 0,
        created_by: 11,
        updated_by: null,
        deleted_by: null,
        created_at: "2000-01-19T05:47:58.000Z",
        updated_at: null,
        deleted_at: null,
        status: 1,
        module_id: 8,
      },
    ],
    search_slug: "cit_drivers_filter",
    searched_value: "",
    search_options: [
      {
        id: 326,
        value: "Driver Code",
      },
      {
        id: 327,
        value: "Driver Name",
      },
      {
        id: 329,
        value: "Driver Mobile",
      },
      {
        id: 330,
        value: "Driver Address",
      },
      {
        id: 331,
        value: "Driving License No",
      },
      {
        id: 332,
        value: "License Issue Place",
      },
      {
        id: 334,
        value: "License Expiry Date",
      },
      {
        id: 335,
        value: "Operating Zone",
      },
    ],
  },
};
